// articles
export const REDUCE_ARTICLES_POINTS = 'REDUCE_ARTICLES_POINTS'
export const RESET_ARTICLES_STATE = 'RESET_ARTICLES_STATE'
export const SET_ARTICLES_LOADED = 'SET_ARTICLES_LOADED'
export const RESET_ARTICLES_LOADED = 'RESET_ARTICLES_LOADED'
export const SET_ARTICLES = 'SET_ARTICLES'

// loader
